USE [ARG10]
GO

/****** Object:  View [dbo].[IMPRIME_COMPROBANTE_ELECTRONICO]    Script Date: 16/04/2018 03:02:19 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








ALTER VIEW [dbo].[IMPRIME_COMPROBANTE_ELECTRONICO]
AS
SELECT * FROM (
SELECT 1 LINEA, A.SOPNUMBE, A.SOPTYPE, A.DOCDATE, A.SUBTOTAL, A.TAXAMNT, A.DOCAMNT, 
A.CUSTNMBR, DUEDATE, CASE WHEN I.DUEDTDS = 0 THEN 'Contado' ELSE CONVERT(VARCHAR,I.DUEDTDS) + ' días' END PYMTRMID, 
CONVERT(INT, A.CUSTNMBR) user_id, A.CUSTNAME, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.CITY, B.STATE, 
B.COUNTRY, B.ZIP, B.PHONE1, 
B.PHONE2, B.FAX, SUBSTRING(B.TXRGNNUM, 1, 25) tax_number, 

ISNULL(LTRIM(RTRIM((CONVERT(CHAR(400), F.TXTFIELD)))) + ' -  ' + ISNULL(H.description, ''), '')  address, 
--F.TXTFIELD address,
CO.CCode address_country_code, 
ISNULL(RTRIM(CONVERT(CHAR(400),D.CMMTTEXT)), '') shipping_address, 
'' shipping_address_country_code, '' license_address, 
'' license_address_country_code,
CONVERT(int, C.INTEGRATIONID) article_id, C.ITEMNMBR, C.ITEMDESC ITEMDESC, 
C.UNITPRCE, 
C.XTNDPRCE, C.QUANTITY, 
ISNULL(E.CMMTTEXT, '') info, C.ShipToName img_url, DYNAMICS.dbo.fncNUMLET(A.CURNCYID, A.DOCAMNT) CURTEXT, 
ISNULL(D.USERDEF1, '') ORDENVTA,
ISNULL(D.USRDAT01, 0) FECHAORDVTA, B.USERDEF1, ISNULL(G.LOCATNNM, '') TRANSFA, ISNULL(G.ADRCNTCT, '') BANCO, 
ISNULL(G.ADDRESS1, '') CUENTA, ISNULL(G.ADDRESS2, '') CBU, ISNULL(G.ADDRESS3, '') TRANSFTIT, CO.ADRCNTCT CMPNYNAM, CO.ADDRESS1 ADDRESS1CO,
CO.ZIPCODE ZIPCODECO, CO.CITY CITYCO, CO.ADDRESS2 TELCO, CO.STATE MAIL1CO, CO.ADDRESS3 MAIL2CO, CO.CMPNYNAM EMPRESA, CO.TAXREGTN,
A.CURNCYID, A.TRDISAMT,
ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'VENTAS'), '') DIRVTAS,
ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'DIRECCION'), '') DIRDIRE,
ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'BANCO'), '') DIRBCO,
C.LNITMSEQ,
(SELECT ITEMDESC FROM IV00101 J WHERE J.ITEMNMBR = C.ITEMNMBR) TITULO,
ISNULL((select TOP 1 CHEKBKID from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKBKID,
A.PYMTRCVD, A.ACCTAMNT, ISNULL((select TOP 1 CHEKNMBR from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKNMBR,
CONVERT(char(1), A.SOPTYPE) sTipo, SUBSTRING(A.SOPNUMBE, 4, 1) sLetra, ISNULL(HD.memo, '') memo, 'SOP10100' sTabla,
dbo.fCfdObtieneImagenC(C.ShipToName) imagenBinaria,
A.CSTPONBR ORDCPRA,
ISNULL(D.USERDEF2, '') TIPOTRABAJO, J.FEI_LETRA1, J.FEI_COD, J.FEI_PDV, J.FEI_NRO, J.FEI_CAE, J.FEI_CAE_DUE, LEFT(CMP.TAXREGTN, 11) CMP_CUIT
FROM
SOP10100 A INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
INNER JOIN SOP10200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
LEFT OUTER JOIN INT_SOPHDR HD ON A.SOPTYPE = HD.SOPTYPE AND A.SOPNUMBE = HD.SOPNUMBE
LEFT OUTER JOIN DYNAMICS..SY01500 CO ON CO.INTERID = DB_NAME()
LEFT OUTER JOIN SOP10106 D ON A.SOPTYPE = D.SOPTYPE AND A.SOPNUMBE = D.SOPNUMBE 
LEFT OUTER JOIN SOP10202 E ON E.SOPTYPE = A.SOPTYPE AND E.SOPNUMBE = A.SOPNUMBE AND E.LNITMSEQ = C.LNITMSEQ
LEFT OUTER JOIN SY03900 F ON A.NOTEINDX = F.NOTEINDX
LEFT OUTER JOIN SY00600 G ON G.LOCATNID = 'BANCO'
LEFT OUTER JOIN INTDB2..ERP_Country_Description H ON B.COUNTRY = H.country_code AND language_code = 'es'
LEFT OUTER JOIN SY03300 I ON A.PYMTRMID = I.PYMTRMID
LEFT OUTER JOIN FEI_SOP30200 J ON A.SOPNUMBE = J.SOPNUMBE AND A.SOPTYPE = J.SOPTYPE
CROSS JOIN DYNAMICS..SY01500 CMP 
WHERE J.FEI_CAE <> '' AND CMP.INTERID = DB_NAME()
) COMPROBANTES
UNION ALL
SELECT * FROM (
SELECT 1 LINEA, A.SOPNUMBE, A.SOPTYPE, A.DOCDATE, A.SUBTOTAL, A.TAXAMNT, A.DOCAMNT, 
A.CUSTNMBR, DUEDATE, CASE WHEN I.DUEDTDS = 0 THEN 'Contado' ELSE CONVERT(VARCHAR,I.DUEDTDS) + ' días' END PYMTRMID, 
CONVERT(INT, A.CUSTNMBR) user_id, A.CUSTNAME, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.CITY, B.STATE, 
B.COUNTRY, B.ZIP, B.PHONE1, 
B.PHONE2, B.FAX, SUBSTRING(B.TXRGNNUM, 1, 25) tax_number, 

ISNULL(LTRIM(RTRIM((CONVERT(CHAR(400), F.TXTFIELD)))) + ' -  ' + ISNULL(H.description, ''), '')  address, 
--F.TXTFIELD address,
CO.CCode address_country_code, 
ISNULL(RTRIM(CONVERT(CHAR(400),D.CMMTTEXT)), '') shipping_address, 
'' shipping_address_country_code, '' license_address, 
'' license_address_country_code,
CONVERT(int, C1.INTEGRATIONID) article_id, C.ITEMNMBR, C.ITEMDESC ITEMDESC, 
C.UNITPRCE, 
C.XTNDPRCE, C.QUANTITY, 
ISNULL(E.CMMTTEXT, '') info, C.ShipToName img_url, DYNAMICS.dbo.fncNUMLET(A.CURNCYID, A.DOCAMNT) CURTEXT, 
ISNULL(D.USERDEF1, '') ORDENVTA,
ISNULL(D.USRDAT01, 0) FECHAORDVTA, B.USERDEF1, ISNULL(G.LOCATNNM, '') TRANSFA, ISNULL(G.ADRCNTCT, '') BANCO, 
ISNULL(G.ADDRESS1, '') CUENTA, ISNULL(G.ADDRESS2, '') CBU, ISNULL(G.ADDRESS3, '') TRANSFTIT, CO.ADRCNTCT CMPNYNAM, CO.ADDRESS1 ADDRESS1CO,
CO.ZIPCODE ZIPCODECO, CO.CITY CITYCO, CO.ADDRESS2 TELCO, CO.STATE MAIL1CO, CO.ADDRESS3 MAIL2CO, CO.CMPNYNAM EMPRESA, CO.TAXREGTN,
A.CURNCYID, A.TRDISAMT,
ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'VENTAS'), '') DIRVTAS,
ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'DIRECCION'), '') DIRDIRE,
ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'BANCO'), '') DIRBCO,
C.LNITMSEQ,
(SELECT ITEMDESC FROM IV00101 J WHERE J.ITEMNMBR = C.ITEMNMBR) TITULO,
ISNULL((select TOP 1 CHEKBKID from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKBKID,
A.PYMTRCVD, A.ACCTAMNT, ISNULL((select TOP 1 CHEKNMBR from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKNMBR,
CONVERT(char(1), A.SOPTYPE) sTipo, SUBSTRING(A.SOPNUMBE, 4, 1) sLetra, ISNULL(HD.memo, '') memo, 'SOP30200' sTabla,
dbo.fCfdObtieneImagenC(C.ShipToName) imagenBinaria,
A.CSTPONBR ORDCPRA,
ISNULL(D.USERDEF2, '') TIPOTRABAJO, J.FEI_LETRA1, J.FEI_COD, J.FEI_PDV, J.FEI_NRO, J.FEI_CAE, J.FEI_CAE_DUE, LEFT(CMP.TAXREGTN, 11) CMP_CUIT
FROM
SOP30200 A INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
INNER JOIN SOP30300 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
LEFT OUTER JOIN INT_SOPLINE C1 ON A.SOPTYPE = C1.SOPTYPE AND A.SOPNUMBE = C1.SOPNUMBE AND C.LNITMSEQ = C1.LNITMSEQ
LEFT OUTER JOIN INT_SOPHDR HD ON A.SOPTYPE = HD.SOPTYPE AND A.SOPNUMBE = HD.SOPNUMBE
LEFT OUTER JOIN DYNAMICS..SY01500 CO ON CO.INTERID = DB_NAME()
LEFT OUTER JOIN SOP10106 D ON A.SOPTYPE = D.SOPTYPE AND A.SOPNUMBE = D.SOPNUMBE 
LEFT OUTER JOIN SOP10202 E ON E.SOPTYPE = A.SOPTYPE AND E.SOPNUMBE = A.SOPNUMBE AND E.LNITMSEQ = C.LNITMSEQ
LEFT OUTER JOIN SY03900 F ON A.NOTEINDX = F.NOTEINDX
LEFT OUTER JOIN SY00600 G ON G.LOCATNID = 'BANCO'
LEFT OUTER JOIN INTDB2..ERP_Country_Description H ON B.COUNTRY = H.country_code AND language_code = 'es'
LEFT OUTER JOIN SY03300 I ON A.PYMTRMID = I.PYMTRMID
LEFT OUTER JOIN FEI_SOP30200 J ON A.SOPNUMBE = J.SOPNUMBE AND A.SOPTYPE = J.SOPTYPE
CROSS JOIN DYNAMICS..SY01500 CMP 
WHERE J.FEI_CAE <> '' AND CMP.INTERID = DB_NAME()
) COMPROBANTES
--WHERE DOCDATE > DATEADD(m, -2, GETDATE())




















GO


