USE [COL10]
GO

--Propósito. Vista de facturación de gila col y getty col
--12/06/17 jcf Modifica join de INT_SOPLINE
--04/12/17 jcf Corrige TAXAMNT
--03/06/19 jcf Elimina convert to int porque da error con algunos datos

ALTER VIEW [dbo].[IMPRIME_COMPROBANTE_UNICO]
AS
SELECT 1 LINEA, A.SOPNUMBE, A.SOPTYPE, A.DOCDATE, A.SUBTOTAL, isnull(IMPU.STAXAMNT, 0)TAXAMNT,
A.DOCAMNT, 
A.CUSTNMBR, DUEDATE, CASE WHEN ISNULL(I.DUEDTDS, 30) = 0 THEN 'Contado' ELSE CONVERT(VARCHAR,ISNULL(I.DUEDTDS, 30)) + ' días' END PYMTRMID, 
A.CUSTNMBR user_id, A.CUSTNAME, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.CITY, B.STATE, 
B.COUNTRY, B.ZIP, B.PHONE1, 
B.PHONE2, B.FAX, A.TXRGNNUM tax_number, 

ISNULL(LTRIM(RTRIM((CONVERT(CHAR(400), F.TXTFIELD)))) + ' -  ' + ISNULL(H.description, ''), '')  address, 
CO.CCode address_country_code, 
ISNULL(RTRIM(CONVERT(CHAR(400),D.CMMTTEXT)), '') shipping_address, 
'' shipping_address_country_code, '' license_address, 
'' license_address_country_code,
C.INTEGRATIONID article_id, C.ITEMNMBR, C.ITEMDESC ITEMDESC, 
C.UNITPRCE, 
C.XTNDPRCE, C.QUANTITY, 
ISNULL(E.CMMTTEXT, '') info, C.ShipToName img_url, 
DYNAMICS.dbo.fncNUMLET(A.CURNCYID, A.SUBTOTAL-A.TRDISAMT+isnull(IMPU.STAXAMNT, 0)) CURTEXT, 

ISNULL(D.USERDEF1, '') ORDENVTA,
ISNULL(D.USRDAT01, 0) FECHAORDVTA, B.USERDEF1, ISNULL(G.LOCATNNM, '') TRANSFA, ISNULL(G.ADRCNTCT, '') BANCO, 
ISNULL(G.ADDRESS1, '') CUENTA, ISNULL(G.ADDRESS2, '') CBU, ISNULL(G.ADDRESS3, '') TRANSFTIT, CO.ADRCNTCT CMPNYNAM, CO.ADDRESS1 ADDRESS1CO,
CO.ZIPCODE ZIPCODECO, CO.CITY CITYCO, CO.ADDRESS2 TELCO, CO.STATE MAIL1CO, CO.ADDRESS3 MAIL2CO, CO.CMPNYNAM EMPRESA, CO.TAXREGTN,
A.CURNCYID, A.TRDISAMT, ISNULL(HD.memo, '') memo,
ISNULL((select TOP 1 CHEKBKID from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKBKID,
ISNULL((select TOP 1 CHEKNMBR from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKNMBR,
'SOP10100' sTabla
FROM
SOP10100 A INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
INNER JOIN SOP10200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
LEFT OUTER JOIN INT_SOPHDR HD ON A.SOPTYPE = HD.SOPTYPE AND A.SOPNUMBE = HD.SOPNUMBE
LEFT OUTER JOIN DYNAMICS..SY01500 CO ON CO.INTERID = DB_NAME()
LEFT OUTER JOIN SOP10106 D ON A.SOPTYPE = D.SOPTYPE AND A.SOPNUMBE = D.SOPNUMBE 
LEFT OUTER JOIN SOP10202 E ON E.SOPTYPE = A.SOPTYPE AND E.SOPNUMBE = A.SOPNUMBE AND E.LNITMSEQ = C.LNITMSEQ
LEFT OUTER JOIN SY03900 F ON A.NOTEINDX = F.NOTEINDX
LEFT OUTER JOIN SY00600 G ON G.LOCATNID = 'BANCO'
LEFT OUTER JOIN INTDB2..ERP_Country_Description H ON B.COUNTRY = H.country_code AND language_code = 'es'
LEFT OUTER JOIN SY03300 I ON A.PYMTRMID = I.PYMTRMID
outer apply (SELECT sum(TX.STAXAMNT) STAXAMNT
			FROM SOP10105 TX 
			WHERE TX.SOPTYPE = A.SOPTYPE 
			AND TX.SOPNUMBE = A.SOPNUMBE
			AND TX.LNITMSEQ = 0 
			AND TAXDTLID LIKE 'V-IVA%'
			) IMPU

UNION ALL

SELECT 1 LINEA, A.SOPNUMBE, A.SOPTYPE, A.DOCDATE, A.SUBTOTAL, isnull(IMPU.STAXAMNT, 0) TAXAMNT,
A.DOCAMNT, 
A.CUSTNMBR, DUEDATE, CASE WHEN ISNULL(I.DUEDTDS, 30) = 0 THEN 'Contado' ELSE CONVERT(VARCHAR,ISNULL(I.DUEDTDS, 30)) + ' días' END PYMTRMID, 
A.CUSTNMBR user_id, A.CUSTNAME, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.CITY, B.STATE, 
B.COUNTRY, B.ZIP, B.PHONE1, 
B.PHONE2, B.FAX, A.TXRGNNUM tax_number, 

ISNULL(LTRIM(RTRIM((CONVERT(CHAR(400), F.TXTFIELD)))) + ' -  ' + ISNULL(H.description, ''), '')  address, 
CO.CCode address_country_code, 
ISNULL(RTRIM(CONVERT(CHAR(400),D.CMMTTEXT)), '') shipping_address, 
'' shipping_address_country_code, '' license_address, 
'' license_address_country_code,
C1.INTEGRATIONID article_id, C.ITEMNMBR, C.ITEMDESC ITEMDESC, 
C.UNITPRCE, 
C.XTNDPRCE, C.QUANTITY, 
ISNULL(E.CMMTTEXT, '') info, C.ShipToName img_url, 

DYNAMICS.dbo.fncNUMLET(A.CURNCYID, A.SUBTOTAL-A.TRDISAMT+isnull(IMPU.STAXAMNT, 0)) CURTEXT,
 
ISNULL(D.USERDEF1, '') ORDENVTA,
ISNULL(D.USRDAT01, 0) FECHAORDVTA, B.USERDEF1, ISNULL(G.LOCATNNM, '') TRANSFA, ISNULL(G.ADRCNTCT, '') BANCO, 
ISNULL(G.ADDRESS1, '') CUENTA, ISNULL(G.ADDRESS2, '') CBU, ISNULL(G.ADDRESS3, '') TRANSFTIT, CO.ADRCNTCT CMPNYNAM, CO.ADDRESS1 ADDRESS1CO,
CO.ZIPCODE ZIPCODECO, CO.CITY CITYCO, CO.ADDRESS2 TELCO, CO.STATE MAIL1CO, CO.ADDRESS3 MAIL2CO, CO.CMPNYNAM EMPRESA, CO.TAXREGTN,
A.CURNCYID, A.TRDISAMT, ISNULL(HD.memo, '') memo,ISNULL((select TOP 1 CHEKBKID from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKBKID,
ISNULL((select TOP 1 CHEKNMBR from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKNMBR,
'SOP30200' sTabla
FROM
SOP30200 A INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
INNER JOIN SOP30300 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
LEFT OUTER JOIN INT_SOPLINE C1 ON A.SOPTYPE = C1.SOPTYPE AND A.SOPNUMBE = C1.SOPNUMBE AND C.LNITMSEQ = C1.LNITMSEQ
LEFT OUTER JOIN INT_SOPHDR HD ON A.SOPTYPE = HD.SOPTYPE AND A.SOPNUMBE = HD.SOPNUMBE
LEFT OUTER JOIN DYNAMICS..SY01500 CO ON CO.INTERID = DB_NAME()
LEFT OUTER JOIN SOP10106 D ON A.SOPTYPE = D.SOPTYPE AND A.SOPNUMBE = D.SOPNUMBE 
LEFT OUTER JOIN SOP10202 E ON E.SOPTYPE = A.SOPTYPE AND E.SOPNUMBE = A.SOPNUMBE AND E.LNITMSEQ = C.LNITMSEQ
LEFT OUTER JOIN SY03900 F ON A.NOTEINDX = F.NOTEINDX
LEFT OUTER JOIN SY00600 G ON G.LOCATNID = 'BANCO'
LEFT OUTER JOIN INTDB2..ERP_Country_Description H ON B.COUNTRY = H.country_code AND language_code = 'es'
LEFT OUTER JOIN SY03300 I ON A.PYMTRMID = I.PYMTRMID
outer apply (SELECT sum(TX.STAXAMNT) STAXAMNT
			FROM SOP10105 TX 
			WHERE TX.SOPTYPE = A.SOPTYPE 
			AND TX.SOPNUMBE = A.SOPNUMBE
			AND TX.LNITMSEQ = 0 
			AND TAXDTLID LIKE 'V-IVA%'
			) IMPU

GO


